site_name: Godot Engine - Kommandoreferenz von A bis Z
docs_dir: book_md_files
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Back to light mode


markdown_extensions:
  - attr_list          # ← Attribute in {…} erlauben
#  - pymdownx.grid
# - pymdownx.superfences   # (empfohlen, nötig für manche Grid-Beispiele)  
#  - pymdownx.tabbed
#  - pymdownx.details


nav:
- Home: index.md
- Innere Vorderteile:
  - Schmutztitel: innere_vorderteile/schmutztitel.md
  - Titelseite: innere_vorderteile/titelseite.md
  - Impressum: innere_vorderteile/impressum.md
  - Vorwort: innere_vorderteile/vorwort.md
  - Inhaltsverzeichnis: innere_vorderteile/inhaltsverzeichnis.md
- Hauptteil:
  - Einleitung: hauptteil/einleitung.md  
  - Referenzen:
    - 'Überblick': hauptteil/referenzen//ueberblick.md
    - 'Kontrollstrukturen':
      - Überblick: hauptteil/referenzen/kontrollstrukturen.md
      - Bedingte Anweisungen: hauptteil/referenzen/kontrollstrukturen/bedingte_anweisungen.md
      - Schleifen: hauptteil/referenzen/kontrollstrukturen/schleifen.md
      - Verzweigungen: hauptteil/referenzen/kontrollstrukturen/verzweigungen.md 
    - 'Dateien verwalten': hauptteil/referenzen/dateien_verwalten.md
    - 'Arbeiten mit der Godot-IDE': hauptteil/referenzen/godot_engine_ide.md
- Anhänge:
  - Anhang A: anhaenge/anhang_a.md
  - Anhang B: anhaenge/anhang_b.md
  - Glossar: anhaenge/glossar.md
  - Bibliographie: anhaenge/bibliographie.md
- Back Matter:
  - Epilog: back_matter/epilog.md
  - Register: back_matter/register.md
  - README: back_matter/README.md
